include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    always_specify_types: true
    omit_local_variable_types: false
    always_use_package_imports: true
    prefer_relative_imports: false
    avoid_print: true
    prefer_single_quotes: true

