name: beatboks
description: "A boxingbag cardio workout app, punching to the beat."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  just_audio: ^0.9.37
  logger: ^2.1.0
  signals: ^4.5.1
  toastification: ^1.2.1
  wakelock_plus: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  image_path: "assets/PNG/beatboksIcon.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/GIF/
    - assets/MP3/
    - assets/PNG/
    - assets/PNG/punches/
