// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcMtSOgsfTjlDzg0ikJRb-xLEIwkoCSgk',
    appId: '1:102127708768:web:a3551155e52de4fe7f7105',
    messagingSenderId: '102127708768',
    projectId: 'beatboks',
    authDomain: 'beatboks.firebaseapp.com',
    storageBucket: 'beatboks.appspot.com',
    measurementId: 'G-LHC073M4Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLiuBQSN5uINit0yPr7A8SgxR-vJ8__wk',
    appId: '1:102127708768:android:0fd22a871e6b63de7f7105',
    messagingSenderId: '102127708768',
    projectId: 'beatboks',
    storageBucket: 'beatboks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_XjE1msgCsauSu5LR_UzOBO6__2Iwak',
    appId: '1:102127708768:ios:beea2f1bf729e1bc7f7105',
    messagingSenderId: '102127708768',
    projectId: 'beatboks',
    storageBucket: 'beatboks.appspot.com',
    iosBundleId: 'dev.plotsklapps.beatboks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE_XjE1msgCsauSu5LR_UzOBO6__2Iwak',
    appId: '1:102127708768:ios:9ca65447606734697f7105',
    messagingSenderId: '102127708768',
    projectId: 'beatboks',
    storageBucket: 'beatboks.appspot.com',
    iosBundleId: 'dev.plotsklapps.beatboks.RunnerTests',
  );
}
